---
abstract: 'Creates an XML Stream connection and parses return data'
author:
  - 'Darian Anthony Patrick <dapatrick@cpan.org>'
build_requires:
  Test::More: 0.92
configure_requires:
  Module::Build: 0.360300
generated_by: 'Module::Build version 0.3607'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Stream
requires:
  Authen::SASL: 0
  Carp: 0
  Encode: 0
  FileHandle: 0
  IO::Select: 0
  IO::Socket: 0
  MIME::Base64: 0
  POSIX: 0
  Sys::Hostname: 0
  perl: v5.8.0
  utf8: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Queue=XML-Stream
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
  repository: http://github.com/dap/XML-Stream
version: 1.23_02
